### ISSUE TITLE
JavaScript error and crash when calling =../2

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#173]
The following call to the `=../2` predicate is expected to throw a `domain_error(non_empty_list,[])` exception but we get a JavaScript error and crash instead:

```text
?- Term =.. [].          
/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:5388
				while( list.indicator === "./2" ) {
				            ^

TypeError: Cannot read property 'indicator' of undefined
    at =../2 (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:5388:17)
    at Thread.step (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2823:13)
    at Thread.again (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2921:13)
    at Thread.answer (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2881:8)
    at Thread.answers (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2896:8)
    at Session.answers (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2886:22)
    at Object.success (/opt/local/share/logtalk-3.40.0-b01/integration/logtalk_tau.js:42:17)
    at parseQuery (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1219:15)
    at Thread.query (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2592:10)
    at Session.query (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2586:22)
```

**Comment by jariazavalverde** [comment]
Fixed by @pmoura in #181 (164947b).
