### ISSUE TITLE
Crash running tests for the atomic_concat/3 predicate

### ISSUE THREAD

**Issue by pmoura** [tau-prolog/tau-prolog#272]
```text
/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1839
		if(options.variable_names) {
		           ^

TypeError: Cannot read property 'variable_names' of undefined
    at Var.toString (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:1839:14)
    at Object.unify (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:4714:10)
    at =/2 (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:5573:17)
    at Thread.step (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2998:13)
    at Thread.again (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:3099:13)
    at Thread.answer (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:3059:8)
    at catch/3 (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:5454:12)
    at Thread.step (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:2998:13)
    at Thread.again (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:3099:13)
    at Object.callback (/Users/pmoura/Documents/Logtalk/tp/node_modules/tau-prolog/modules/core.js:5452:12)
```

**Comment by jariazavalverde** [comment]
Fixed.

**Comment by pmoura** [comment]
All tests pass after the fix:

```text
$ logtalk_tester -p tau -g "set_logtalk_flag(clean,off)" -w
% Batch testing started @ 2021-11-09 10:00:31
%         Logtalk version: 3.52.0-b03
%         Tau Prolog version: 0.3.1
%
% Documents/Logtalk/logtalk3/tests/prolog/predicates/atomic_concat_3
%         8 tests: 0 skipped, 8 passed, 0 failed (0 flaky)
%         completed tests from object tests in 30 seconds
%         clause coverage n/a
%
% 1 test sets: 1 completed, 0 skipped, 0 broken, 0 timedout, 0 crashed
% 8 tests: 0 skipped, 8 passed, 0 failed (0 flaky)
%
% Batch testing ended @ 2021-11-09 10:01:06
```
