### ISSUE TITLE
(^)/2 incorrect overflow

### ISSUE THREAD

**Issue by UWN** [tau-prolog/tau-prolog#310]
```
X is 3^3^4.
uncaught exception: error(type_error(float,3),is/2), unexpected
```

BTW, is there some *simple* way/instruction to use Tau from a Linux-shell? I am not really accustomed with all these net-technologies.

**Comment by jariazavalverde** [comment]
> BTW, is there some simple way/instruction to use Tau from a Linux-shell? I am not really accustomed with all these net-technologies.

I just added the REPL script that we use with Logtalk. There are things to improve, but it can do the job. Clone the repo and run the command `node taupl.js` (you need [node.js](https://nodejs.org)).

**Comment by jariazavalverde** [comment]
You need to install the `readline-sync` package. 

```npm install -g readline-sync```

**Comment by UWN** [comment]
```
 2023  node taupl.js 
 2024  node --version
 2025  npm install -g readline-sync
 2026  sudo apt install npm
 2027  npm install -g readline-sync
 2028  sudo npm install -g readline-sync
 2029  node taupl.js ~
 2030  node taupl.js
```
Still same error

**Comment by UWN** [comment]
```
ulrich@TU-Wien:/opt/gupu/tau-prolog$ npm i
loadDep:readline-sync → 2 ▄ ╢████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine qunit@2.19.1: wanted: {"node":">=10"} (current: {"node":"8.1npm ERR! Linux 5.4.0-107-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/gupu/tau-prolog/npm-debug.log

**Comment by jariazavalverde** [comment]
Mmm, try to install locally `readline-sync` with `npm install readline-sync`. If not, you have to update node to the latest version and run `npm i` again.

**Comment by UWN** [comment]
Thanks anyway. Tried it on Ubuntu 18.04.5 LTS and Ubuntu 21.10.

**Comment by UWN** [comment]
(on 21.10 it's now running,thx)
